vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%app.path.product%'
            upload_destination: '%kernel.project_dir%/public%app.path.product%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
